// src/app/layout.tsx
import { Providers } from "@/redux/provider";
import "./globals.css";
import ClientLayout from "./components/ClientLayout";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <ClientLayout>{children}</ClientLayout> {/* Use ClientLayout here */}
        </body>
      </html>
    </Providers>
  );
}
